// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbYPHGyqgR3J1D74pwImFr9Tvbld8NgMk',
    appId: '1:615505091780:web:9835319e1b3ef29212fd91',
    messagingSenderId: '615505091780',
    projectId: 'last-d84e4',
    authDomain: 'last-d84e4.firebaseapp.com',
    databaseURL: 'https://last-d84e4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'last-d84e4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL7FX7tPqp21VzEAFOvuR9BZd_JjsxVYg',
    appId: '1:615505091780:android:4ee4d608f54777ec12fd91',
    messagingSenderId: '615505091780',
    projectId: 'last-d84e4',
    databaseURL: 'https://last-d84e4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'last-d84e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-xs3wKZYKBHG-tr2LZSdWyBbxU8b6k1o',
    appId: '1:615505091780:ios:78d55ae548b9c5b512fd91',
    messagingSenderId: '615505091780',
    projectId: 'last-d84e4',
    databaseURL: 'https://last-d84e4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'last-d84e4.appspot.com',
    iosBundleId: 'com.example.agelgilApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-xs3wKZYKBHG-tr2LZSdWyBbxU8b6k1o',
    appId: '1:615505091780:ios:78d55ae548b9c5b512fd91',
    messagingSenderId: '615505091780',
    projectId: 'last-d84e4',
    databaseURL: 'https://last-d84e4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'last-d84e4.appspot.com',
    iosBundleId: 'com.example.agelgilApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSHMBCRJCEODFmYVge7mOIX1aBVon7lcc',
    appId: '1:615505091780:web:df96dadd50267aa712fd91',
    messagingSenderId: '615505091780',
    projectId: 'last-d84e4',
    authDomain: 'last-d84e4.firebaseapp.com',
    databaseURL: 'https://last-d84e4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'last-d84e4.appspot.com',
  );

}